# Generated by Django 4.1.5 on 2024-01-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0066_teamprofile_alter_service_team_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='more_photos',
            field=models.ImageField(blank=True, null=True, upload_to='mediafiles'),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='team_profile',
            field=models.ImageField(blank=True, null=True, upload_to='mediafiles'),
        ),
    ]
